#pragma once

// AZCT own-key integration. We re-encrypt the client's AZFNPROTENC canaries under our own keys (see
// AzctCanary.h, generated by tools/azct_decrypt.py) and patch them in, so the client's native validator
// (0x144125da0) accepts our key instead of the vendor's - no stub, legitimate validation.

namespace uoa::azct {

void install();   // patch the re-keyed canaries into the client's .text at boot

}
