#pragma once
#include <cstdint>

// GENERATED by _tools/rebase - do not edit by hand. Re-run rebase.py after a client update.
// AUTH channel offsets, each located by a shift-robust byte signature.

namespace uoa::off {

inline constexpr uint32_t kKdf = 0x41262c0;   // AZ-TICKET-v1 KDF (TicketProbe fixes its session fields)
inline constexpr uint32_t kFinalize = 0x5f6e9c0;   // digest finalize (ProofBridge overwrites its output)
inline constexpr uint32_t kA3Handler = 0x412c09d;   // opcode-0xA3 handler
inline constexpr uint32_t kA1Handler = 0x412a070;   // opcode-0xA1 SRP-challenge handler (AuthProbe hooks it)
inline constexpr uint32_t kAzctValidator = 0x41253c0;   // AZCT slot validator (AES-CTR decrypt + CRC)
inline constexpr uint32_t kLoginToWorld = 0x4129750;   // native world-login entry: LoginToWorld(subsystem, nameFString, addrFString)
inline constexpr uint32_t kMangosPump = 0x4837a10;   // native login pump; inline operands yield the subsystem accessor, FName ctor, collection global
inline constexpr uint32_t kFNameCtor = 0x12aed80;
inline constexpr uint32_t kGetSubsystem = 0x458e0f0;
inline constexpr uint32_t kSubsysCollection = 0x8166868;

} // namespace uoa::off
