#pragma once
#include <cstdint>

// GENERATED by tools/resolve_offsets.py - do not edit by hand.
// Each RVA located by a shift-robust byte signature; re-run the tool after a client update.

namespace uoa::off {

inline constexpr uint32_t kReadiness = 0x4129310;
inline constexpr uint32_t kDiscGate = 0x34e3e37;
inline constexpr uint32_t kFlagJne = 0x412c192;
inline constexpr uint32_t kKdf = 0x41260a0;
inline constexpr uint32_t kA3Handler = 0x412be7d;
inline constexpr uint32_t kA1Handler = 0x4129e50;
inline constexpr uint32_t kAzctValidator = 0x41251a0;
inline constexpr uint32_t kTeardown = 0x474ef20;
inline constexpr uint32_t kFinalize = 0x5f695c0;
inline constexpr uint32_t kLoginToWorld = 0x4129530;
inline constexpr uint32_t kMangosPump = 0x4802840;
inline constexpr uint32_t kFNameCtor = 0x12aeca0;
inline constexpr uint32_t kGetSubsystem = 0x458e2a0;
inline constexpr uint32_t kSubsysCollection = 0x815f868;

} // namespace uoa::off
