#pragma once
#include <cstdint>

// GENERATED by _tools/rebase - do not edit by hand. Re-run rebase.py after a client update.
// Protocol-stable WORLD opcode numbers + struct offsets (constants), paired with the
// freshly resolved handler RVAs so the wire number and its handler travel together.

namespace uoa::wop {

// opcode numbers
inline constexpr int kLoginVerifyWorld = 0xC5;   // map-verify (S->C); its handler is kMapVerify
inline constexpr int kCompressedUpdate = 0x1FC;   // compressed object update (S->C); handler kCompressedUpdateHandler
inline constexpr int kCharEnum = 0x478;   // char-enum reply (S->C)
inline constexpr int kWorldAccess = 0x527;   // world-access grant (S->C); handler kWorldAccessHandler
inline constexpr int kPawnSpawn = 0x102;   // synthesized pawn-spawn (S->C); handler kMapPawnHandler
inline constexpr int kReadyAck = 0x103;   // ready-ack (C->S, dropped)
inline constexpr int kAuthResponse = 0x1EE;   // auth-response (S->C); handler kAuthResponseHandler
inline constexpr int kAuthChallenge = 0x1EC;   // auth-challenge (S->C)

// struct offsets / bounds
inline constexpr int kWorldReadyByte = 0x646;   // world-ready byte at this+0x646 (values 0/1/2)
inline constexpr int kDispatchTable = 0x6D0;   // dispatch table at session+0x6D0
inline constexpr int kEntryStride = 0x18;   // dispatch entry stride in bytes (+0x00 handler ptr, +0x08 adjust i32, +0x10 extra)
inline constexpr int kMaxOpcode = 0x528;   // max opcode (table bound)
inline constexpr int kWorldAccessFlag = 0x8348;   // world-access restricted flag at session+0x8348
inline constexpr int kWorldAccessTime = 0x834C;   // world-access time at session+0x834C

// opcode -> resolved handler RVA (cross-checked against the world offsets)
inline constexpr uint32_t kHandler_0xC5 = 0x4956950;   // kMapVerify
inline constexpr uint32_t kHandler_0x1FC = 0x49532b0;   // kCompressedUpdateHandler
inline constexpr uint32_t kHandler_0x527 = 0x495cfd0;   // kWorldAccessHandler
inline constexpr uint32_t kHandler_0x102 = 0x495b7e0;   // kMapPawnHandler
inline constexpr uint32_t kHandler_0x1EE = 0x4952070;   // kAuthResponseHandler

} // namespace uoa::wop
